sudo: required
services:
    - docker

before_install:
    - docker build -t v2dev7/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true v2dev7/react-test npm test -- -- coverage

after_success:
    - docker build -t v2dev7/multi-client ./client
    - docker build -t  v2dev7/multi-nginx ./nginx
    - docker build -t v2dev7/multi-server ./server
    - docker build -t v2dev7/multi-worker ./worker

    # Log in to the docker CLI. Make sure Docker id and Docker password matches in the travis-ci.org
    - echo "$Docker_password" | docker login -u "$Docker_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push v2dev7/multi-client
    - docker push v2dev/multi-nginx
    - docker push v2dev7/multi-server
    - docker push v2dev7/multi-worker

